# Generated by Django 5.2.6 on 2026-03-16 06:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Recovery_DP', '0001_initial'),
        ('modelmasterapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BathNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bath_number', models.CharField(max_length=100)),
                ('bath_type', models.CharField(choices=[('Bright', 'Bright'), ('Semi Bright', 'Semi Bright'), ('Dull', 'Dull')], help_text='Type of bath this number belongs to', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Is this bath number active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bath Number',
                'verbose_name_plural': 'Bath Numbers',
                'unique_together': {('bath_number', 'bath_type')},
            },
        ),
        migrations.CreateModel(
            name='Jig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jig_qr_id', models.CharField(help_text='Unique Jig QR ID', max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_loaded', models.BooleanField(default=False, help_text='Is this Jig currently loaded?')),
                ('locked_at', models.DateTimeField(blank=True, help_text='When the jig was locked for draft', null=True)),
                ('drafted', models.BooleanField(default=False, help_text='Is this Jig currently drafted?')),
                ('batch_id', models.CharField(blank=True, help_text='Batch ID for which Jig is locked', max_length=100, null=True)),
                ('lot_id', models.CharField(blank=True, help_text='Lot ID for which Jig is locked', max_length=100, null=True)),
                ('current_user', models.ForeignKey(blank=True, help_text='User currently using this jig', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JigLoadingMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jig_type', models.CharField(help_text='Jig Type', max_length=100)),
                ('jig_capacity', models.IntegerField(help_text='Jig Capacity')),
                ('forging_info', models.CharField(help_text='Forging Info', max_length=100)),
                ('model_stock_no', models.ForeignKey(help_text='Model Stock Number', on_delete=django.db.models.deletion.CASCADE, to='modelmasterapp.modelmaster')),
            ],
        ),
        migrations.CreateModel(
            name='JigLoadTrayId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_id', models.CharField(blank=True, db_index=True, help_text='Lot ID', max_length=50, null=True)),
                ('tray_id', models.CharField(help_text='Tray ID', max_length=100)),
                ('tray_quantity', models.IntegerField(blank=True, help_text='Quantity in the tray', null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('top_tray', models.BooleanField(default=False)),
                ('delink_tray', models.BooleanField(default=False, help_text='Is tray delinked')),
                ('delink_tray_qty', models.CharField(blank=True, help_text='Delinked quantity', max_length=50, null=True)),
                ('broken_hooks_effective_tray', models.BooleanField(default=False, help_text='Is tray part of effective quantity after broken hooks')),
                ('broken_hooks_excluded_qty', models.IntegerField(default=0, help_text='Quantity excluded due to broken hooks')),
                ('effective_tray_qty', models.IntegerField(blank=True, help_text='Effective quantity for this tray after broken hooks calculation', null=True)),
                ('IP_tray_verified', models.BooleanField(default=False, help_text='Is tray verified in IP')),
                ('rejected_tray', models.BooleanField(default=False, help_text='Is tray rejected')),
                ('new_tray', models.BooleanField(default=True, help_text='Is tray new')),
                ('tray_type', models.CharField(blank=True, help_text='Type of tray (Jumbo, Normal, etc.) - filled by admin', max_length=50, null=True)),
                ('tray_capacity', models.IntegerField(blank=True, help_text='Capacity of this specific tray - filled by admin', null=True)),
                ('batch_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modelmasterapp.modelmastercreation')),
                ('recovery_batch_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Recovery_DP.recoverymastercreation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Jig Load Tray ID',
                'verbose_name_plural': 'Jig Load Tray IDs',
            },
        ),
        migrations.CreateModel(
            name='JigAutoSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_id', models.CharField(db_index=True, max_length=100)),
                ('batch_id', models.CharField(db_index=True, max_length=100)),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('auto_save_data', models.JSONField(blank=True, default=dict, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'batch_id', 'lot_id', 'updated_at'], name='Jig_Loading_user_id_77a274_idx')],
                'unique_together': {('user', 'batch_id', 'lot_id')},
            },
        ),
        migrations.CreateModel(
            name='JigCompleted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(db_index=True, max_length=100)),
                ('lot_id', models.CharField(db_index=True, max_length=100)),
                ('draft_data', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jig_cases_remaining_count', models.IntegerField(blank=True, default=0, null=True)),
                ('updated_lot_qty', models.IntegerField(blank=True, default=0, null=True)),
                ('original_lot_qty', models.IntegerField(blank=True, default=0, null=True)),
                ('jig_id', models.CharField(blank=True, max_length=100, null=True)),
                ('delink_tray_info', models.JSONField(blank=True, default=list, null=True)),
                ('delink_tray_qty', models.IntegerField(blank=True, default=0, null=True)),
                ('delink_tray_count', models.IntegerField(blank=True, default=0, null=True)),
                ('half_filled_tray_info', models.JSONField(blank=True, default=list, null=True)),
                ('half_filled_tray_qty', models.IntegerField(blank=True, default=0, null=True)),
                ('jig_capacity', models.IntegerField(blank=True, default=0, null=True)),
                ('broken_hooks', models.IntegerField(blank=True, default=0, null=True)),
                ('loaded_cases_qty', models.IntegerField(blank=True, default=0, null=True)),
                ('plating_stock_num', models.CharField(blank=True, max_length=100, null=True)),
                ('draft_status', models.CharField(choices=[('active', 'Active'), ('submitted', 'Submitted')], default='active', max_length=20)),
                ('hold_status', models.CharField(blank=True, default='normal', max_length=20, null=True)),
                ('is_multi_model', models.BooleanField(default=False)),
                ('jig_position', models.CharField(blank=True, max_length=100, null=True)),
                ('IP_loaded_date_time', models.DateTimeField(blank=True, null=True)),
                ('last_process_module', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('pick_remarks', models.TextField(blank=True, null=True)),
                ('no_of_model_cases', models.TextField(blank=True, null=True)),
                ('partial_lot_id', models.CharField(blank=True, help_text='New lot ID for remaining cases in partial submission', max_length=100, null=True)),
                ('bath_numbers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Jig_Loading.bathnumbers')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Jig Completed',
                'verbose_name_plural': 'Jig Completed',
                'unique_together': {('batch_id', 'lot_id', 'user')},
            },
        ),
        migrations.CreateModel(
            name='JigLoadingManualDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(db_index=True, max_length=100)),
                ('lot_id', models.CharField(db_index=True, max_length=100)),
                ('draft_data', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jig_cases_remaining_count', models.IntegerField(blank=True, default=0, null=True)),
                ('updated_lot_qty', models.IntegerField(blank=True, default=0, null=True)),
                ('original_lot_qty', models.IntegerField(blank=True, default=0, null=True)),
                ('jig_id', models.CharField(blank=True, max_length=100, null=True)),
                ('delink_tray_info', models.JSONField(blank=True, default=list, null=True)),
                ('delink_tray_qty', models.IntegerField(blank=True, default=0, null=True)),
                ('delink_tray_count', models.IntegerField(blank=True, default=0, null=True)),
                ('half_filled_tray_info', models.JSONField(blank=True, default=list, null=True)),
                ('half_filled_tray_qty', models.IntegerField(blank=True, default=0, null=True)),
                ('jig_capacity', models.IntegerField(blank=True, default=0, null=True)),
                ('broken_hooks', models.IntegerField(blank=True, default=0, null=True)),
                ('loaded_cases_qty', models.IntegerField(blank=True, default=0, null=True)),
                ('plating_stock_num', models.CharField(blank=True, max_length=100, null=True)),
                ('draft_status', models.CharField(choices=[('active', 'Active'), ('submitted', 'Submitted')], default='active', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('batch_id', 'lot_id', 'user')},
            },
        ),
    ]
