# Generated by Django 5.2.6 on 2025-12-31 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jig_Loading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jig',
            name='lot_id',
            field=models.CharField(blank=True, help_text='Lot ID for which Jig is locked', max_length=100, null=True),
        ),
    ]
