# Generated by Django 5.2.5 on 2025-12-31 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jig_Loading', '0002_jig_lot_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='jigdetails',
            name='broken_buildup_hooks',
            field=models.IntegerField(default=0, help_text='Number of broken buildup hooks'),
        ),
    ]
