# Generated by Django 5.2.5 on 2026-01-17 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jig_Loading', '0002_remove_jigdetails_bath_numbers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jigcompleted',
            name='hold_status',
            field=models.CharField(blank=True, default='normal', max_length=20, null=True),
        ),
    ]
