# Generated by Django 5.2.5 on 2025-12-31 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jig_Loading', '0003_jigdetails_broken_buildup_hooks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jigdetails',
            name='broken_buildup_hooks',
        ),
        migrations.AddField(
            model_name='jigdetails',
            name='broken_hooks',
            field=models.IntegerField(default=0, help_text='Number of broken hooks'),
        ),
    ]
