# Generated by Django 5.2.5 on 2026-01-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jig_Loading', '0004_remove_jigdetails_broken_buildup_hooks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jigloadingmanualdraft',
            name='tray_distribution',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
