# Generated by Django 5.2.5 on 2026-01-17 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jig_Loading', '0003_rename_jig_loading__user_ba_ba9b8_idx_jig_loading_user_id_77a274_idx_and_more'),
        ('Jig_Loading', '0004_add_missing_fields'),
    ]

    operations = [
    ]
