# Generated by Django 5.2.5 on 2026-01-03 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jig_Loading', '0005_jigloadingmanualdraft_tray_distribution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jigloadingmanualdraft',
            name='tray_distribution',
        ),
        migrations.AddField(
            model_name='jigloadtrayid',
            name='broken_hooks_effective_tray',
            field=models.BooleanField(default=False, help_text='Is tray part of effective quantity after broken hooks'),
        ),
        migrations.AddField(
            model_name='jigloadtrayid',
            name='broken_hooks_excluded_qty',
            field=models.IntegerField(default=0, help_text='Quantity excluded due to broken hooks'),
        ),
        migrations.AddField(
            model_name='jigloadtrayid',
            name='effective_tray_qty',
            field=models.IntegerField(blank=True, help_text='Effective quantity for this tray after broken hooks calculation', null=True),
        ),
    ]
