# Generated by Django 5.2.5 on 2026-01-05 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jig_Loading', '0006_remove_jigloadingmanualdraft_tray_distribution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jigloadingmanualdraft',
            name='jig_cases_remaining_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='jigloadingmanualdraft',
            name='updated_lot_qty',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
