# Generated by Django 5.2.5 on 2026-01-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jig_Loading', '0007_jigloadingmanualdraft_jig_cases_remaining_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jigloadingmanualdraft',
            name='original_lot_qty',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
