# Generated by Django 5.2.5 on 2026-01-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jig_Loading', '0008_jigloadingmanualdraft_original_lot_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='jigloadingmanualdraft',
            name='tray_info',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
