# Generated by Django 5.2.5 on 2026-01-05 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jig_Loading', '0009_jigloadingmanualdraft_tray_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='jigdetails',
            name='original_lot_qty',
            field=models.IntegerField(blank=True, default=0, help_text='Original lot quantity before jig loading', null=True),
        ),
        migrations.AddField(
            model_name='jigdetails',
            name='tray_info',
            field=models.JSONField(blank=True, default=list, help_text='Tray information for this jig', null=True),
        ),
        migrations.AddField(
            model_name='jigdetails',
            name='updated_lot_qty',
            field=models.IntegerField(blank=True, default=0, help_text='Updated lot quantity after jig loading', null=True),
        ),
    ]
