# Generated by Django 5.2.5 on 2026-01-05 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jig_Loading', '0010_jigdetails_original_lot_qty_jigdetails_tray_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jigdetails',
            name='original_lot_qty',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='jigdetails',
            name='tray_info',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='jigdetails',
            name='updated_lot_qty',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
