# Generated by Django 5.2.5 on 2025-10-08 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jig_Loading', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JigLotTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jig_qr_id', models.CharField(db_index=True, help_text='Jig QR ID', max_length=100)),
                ('lot_id', models.CharField(db_index=True, help_text='Lot ID being tracked', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Is this tracking record active')),
                ('is_drafted', models.BooleanField(default=False, help_text='Is this lot currently in draft state')),
                ('is_loaded', models.BooleanField(default=False, help_text='Is this lot currently loaded')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who loaded/drafted the lot', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['jig_qr_id', 'is_active'], name='Jig_Loading_jig_qr__82f9c0_idx'), models.Index(fields=['lot_id', 'is_active'], name='Jig_Loading_lot_id_536137_idx')],
                'unique_together': {('jig_qr_id', 'lot_id')},
            },
        ),
    ]
