# Generated by Django 5.2.6 on 2025-10-21 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jig_Loading', '0002_jiglottracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jiglottracking',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='jiglottracking',
            name='user',
        ),
        migrations.RemoveConstraint(
            model_name='jigautosave',
            name='unique_user_lot',
        ),
        migrations.RemoveConstraint(
            model_name='jigautosave',
            name='unique_session_lot',
        ),
        migrations.RemoveIndex(
            model_name='jigautosave',
            name='Jig_Loading_session_53c463_idx',
        ),
        migrations.AddField(
            model_name='jig',
            name='jig_type',
            field=models.CharField(default=1, help_text='Permanent Jig Type', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jigautosave',
            name='session_key',
            field=models.CharField(blank=True, default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jigautosave',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='jigautosave',
            unique_together={('user', 'lot_id')},
        ),
        migrations.DeleteModel(
            name='JigLotTracking',
        ),
    ]
