# Generated by Django 5.2.6 on 2025-10-21 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jig_Loading', '0003_alter_jiglottracking_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jig',
            name='jig_type',
        ),
    ]
