# Generated by Django 5.2.6 on 2025-11-19 08:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jig_Loading', '0005_jigloadingmanualdraft'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='jigautosave',
            name='Jig_Loading_user_id_b2eefd_idx',
        ),
        migrations.AlterUniqueTogether(
            name='jigautosave',
            unique_together={('user', 'batch_id', 'lot_id')},
        ),
        migrations.AddField(
            model_name='jigautosave',
            name='auto_save_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='jigautosave',
            name='batch_id',
            field=models.CharField(db_index=True, default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='jigautosave',
            index=models.Index(fields=['user', 'batch_id', 'lot_id', 'updated_at'], name='Jig_Loading_user_id_77a274_idx'),
        ),
        migrations.RemoveField(
            model_name='jigautosave',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='jigautosave',
            name='delink_tray_data',
        ),
        migrations.RemoveField(
            model_name='jigautosave',
            name='empty_slots',
        ),
        migrations.RemoveField(
            model_name='jigautosave',
            name='faulty_slots',
        ),
        migrations.RemoveField(
            model_name='jigautosave',
            name='half_filled_tray_data',
        ),
        migrations.RemoveField(
            model_name='jigautosave',
            name='jig_qr_id',
        ),
        migrations.RemoveField(
            model_name='jigautosave',
            name='lot_id_quantities',
        ),
        migrations.RemoveField(
            model_name='jigautosave',
            name='no_of_cycle_count',
        ),
        migrations.RemoveField(
            model_name='jigautosave',
            name='selected_model_nos',
        ),
        migrations.RemoveField(
            model_name='jigautosave',
            name='total_cases_loaded',
        ),
    ]
