# Generated by Django 5.2.6 on 2026-03-16 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Brass_QC', '0001_initial'),
        ('modelmasterapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='brasstrayid',
            name='batch_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modelmasterapp.modelmastercreation'),
        ),
        migrations.AddField(
            model_name='brasstrayid',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='brass_qc_draft_store',
            unique_together={('lot_id', 'draft_type')},
        ),
        migrations.AlterUniqueTogether(
            name='brass_toptray_draft_store',
            unique_together={('lot_id',)},
        ),
        migrations.AlterUniqueTogether(
            name='brasstrayid',
            unique_together={('lot_id', 'tray_id')},
        ),
    ]
