# Generated by Django 5.2.6 on 2025-11-26 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jig_Loading', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jigloadingmaster',
            name='jig_capacity',
            field=models.IntegerField(blank=True, default=0, help_text='Jig Capacity', null=True),
        ),
    ]
