# Generated by Django 5.2.5 on 2025-12-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jig_Loading', '0002_alter_jigloadingmaster_jig_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='jigdetails',
            name='broken_hooks',
            field=models.IntegerField(default=0),
        ),
    ]
