# Generated by Django 5.2.6 on 2026-03-16 06:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InprocessInspectionTrayCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_capacity', models.IntegerField(help_text='Custom capacity for this tray type in Inprocess Inspection')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this custom capacity is active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this custom capacity', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inprocess Inspection Tray Capacity',
                'verbose_name_plural': 'Inprocess Inspection Tray Capacities',
            },
        ),
    ]
